AWSTemplateFormatVersion: 2010-09-09
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0d5eff06f840b45e9
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref SecurityGroup
      KeyName: teja
      UserData: !Base64 
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash -xe
            - |
              yum update -y
            - >
              trap "/opt/aws/bin/cfn-signal --exit-code 1 --resource
              WebServerGroup --region ${AWS::Region} --stack ${AWS::StackName}"
              ERR
            - |
              yum install python-pip git mysql -y
            - |
              sudo git clone "https://github.com/TejaSrini/access-RDS-via-Python.git"
            - |
              pip install flask
            - |
              sudo yum -y install python python-devel mysql-devel redhat-rpm-config gcc
            - |
              sudo pip install flask_mysqldb
            - |
              cd ..
            - |
              cd ..
            - |
              cd access-RDS-via-Python
            - |
              sudo python app.py
            - >
              /opt/aws/bin/cfn-signal --exit-code 0 --resource WebServerGroup
              --region ${AWS::Region} --stack ${AWS::StackName}
      Tags:
        - Key: name
          Value: teja
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 8c280bf3-47dd-4cd4-8657-5823fc4c8ccb
  ElasticLoadBalancer:
    Type: 'AWS::ElasticLoadBalancing::LoadBalancer'
    Properties:
      AvailabilityZones: !GetAZs ''
      Instances:
        - !Ref EC2Instance
      Listeners:
        - LoadBalancerPort: '80'
          InstancePort: '80'
          Protocol: HTTP
      HealthCheck:
        Target: 'HTTP:80/'
        HealthyThreshold: '3'
        UnhealthyThreshold: '5'
        Interval: '30'
        Timeout: '5'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: f1557da4-3d67-4168-983e-870595e0aabe
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: ' HTTP SSH access'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '3306'
          ToPort: '3306'
          CidrIp: 0.0.0.0/0
    Metadata:
      'AWS::CloudFormation::Designer':
        id: b7fac43b-3311-4707-a88e-d2a781c165bd
  RDSDBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBSecurityGroups:
        - Ref: DBSecurityGroup
      AllocatedStorage: '20'
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: database-teja
      Engine: MySQL
      EngineVersion: 8.0.16
      MasterUsername: teja
      MasterUserPassword: teja8352
      Port: '3306'
      PubliclyAccessible: 'false'
      Tags:
        - Key: name
          Value: teja
    Metadata:
      'AWS::CloudFormation::Designer':
        id: c9f476e2-93f5-4947-a632-1b30b7651970
  DBSecurityGroup:
    Type: 'AWS::RDS::DBSecurityGroup'
    Properties:
      GroupDescription: ' HTTP SSH access'
      DBSecurityGroupIngress:
        EC2SecurityGroupName:
          Ref: SecurityGroup
    Metadata:
      'AWS::CloudFormation::Designer':
        id: ea80b9eb-eea9-435e-b9f5-6c1a1c550757
Metadata:
  'AWS::CloudFormation::Designer':
    b7fac43b-3311-4707-a88e-d2a781c165bd:
      size:
        width: 60
        height: 60
      position:
        x: 30
        'y': 40
      z: 1
      embeds: []
    ea80b9eb-eea9-435e-b9f5-6c1a1c550757:
      size:
        width: 60
        height: 60
      position:
        x: 280
        'y': 60
      z: 1
      embeds: []
    c9f476e2-93f5-4947-a632-1b30b7651970:
      size:
        width: 60
        height: 60
      position:
        x: 10
        'y': 270
      z: 1
      embeds: []
      isassociatedwith:
        - ea80b9eb-eea9-435e-b9f5-6c1a1c550757
    8c280bf3-47dd-4cd4-8657-5823fc4c8ccb:
      size:
        width: 60
        height: 60
      position:
        x: 260
        'y': 200
      z: 1
      embeds: []
      isassociatedwith:
        - b7fac43b-3311-4707-a88e-d2a781c165bd
    f1557da4-3d67-4168-983e-870595e0aabe:
      size:
        width: 60
        height: 60
      position:
        x: 480
        'y': 260
      z: 1
      embeds: []
      isassociatedwith:
        - 8c280bf3-47dd-4cd4-8657-5823fc4c8ccb
